apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx-sts
  serviceName: "nginx-sts"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-sts
        image: nginx:1.26.3-alpine3.20-perl
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "cstor"
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sts
  namespace: test
  labels: 
    run: nginx-sts
spec: 
  type: LoadBalancer  
  selector:
    app: nginx-sts  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-sts-ingress
  namespace: test  
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-sts.local
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: nginx-sts
            port:
              number: 80